steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - function
  - deploy
  - get-baltimore-city-employee-salaries-v3
  - --region=us-central1
  - --source=https://source.developers.google.com/projects/${_PROJECT_ID}/repos/${_REPO}
  - --entry-point=main
  - --trigger-http
  - --runtime=python311