steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - get-baltimore-city-employee-salaries-v3
  - --region=us-central1
  - --source=https://source.developers.google.com/projects/$PROJECT_ID/repos/$REPO
  - --entry-point=main
  - --trigger-http
  - --runtime=python311