steps:
  options:
    logging: CLOUD_LOGGING_ONLY
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/open-baltimore-data/github.com/jmathena1/baltimore-city-employee-salaries', '-f', 'Dockerfile', .]