steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - get-baltimore-city-employee-salaries-v3
  - --region=us-central1
  - --source=github_jmathena1_baltimore-city-employee-salaries
  - --trigger-http
  - --runtime=python311